@startuml

title __REMOTE_INTERFACES's Class Diagram__\n

  namespace common {
    namespace remote_interfaces {
      interface common.remote_interfaces.RemoteLoginController {
          {abstract} + joinLobby()
          {abstract} + login()
          {abstract} + register()
      }
    }
  }
  

  namespace common {
    namespace remote_interfaces {
      interface common.remote_interfaces.RemotePlayer {
          {abstract} + chooseAmmo()
          {abstract} + chooseAsynchronousEffectOrder()
          {abstract} + chooseDirection()
          {abstract} + chooseMap()
          {abstract} + chooseNumberOfSkulls()
          {abstract} + choosePcColour()
          {abstract} + choosePowerUp()
          {abstract} + chooseSquare()
          {abstract} + chooseTarget()
          {abstract} + chooseUpgrade()
          {abstract} + chooseWeaponOfMine()
          {abstract} + chooseWeaponOnSpawnPoint()
          {abstract} + getToken()
          {abstract} + grabStuff()
          {abstract} + isConnected()
          {abstract} + ok()
          {abstract} + pass()
          {abstract} + quit()
          {abstract} + reload()
          {abstract} + response()
          {abstract} + runAround()
          {abstract} + sendMessage()
          {abstract} + shootPeople()
          {abstract} + skip()
          {abstract} + switchFireMode()
          {abstract} + undo()
          {abstract} + usePowerUp()
      }
    }
  }
  

  namespace common {
    namespace remote_interfaces {
      interface common.remote_interfaces.RemoteView {
          {abstract} + ack()
          {abstract} + chatMessage()
          {abstract} + close()
          {abstract} + getListener()
          {abstract} + isReachable()
          {abstract} + notifyEvent()
          {abstract} + request()
          {abstract} + resumeGame()
          {abstract} + winners()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
