@startuml

title __SQUARES's Class Diagram__\n

  namespace server {
    namespace model {
      namespace squares {
        class server.model.squares.AmmoSquare {
            - ammoDeck : Deck<AmmoTile>
            + AmmoSquare()
            + AmmoSquare()
            + collect()
            + convertToDTO()
            + getAmmoTile()
            + init()
            + isEmpty()
            + isSpawnPoint()
            + itemToString()
            + refill()
        }
      }
    }
  }
  

  namespace server {
    namespace model {
      namespace squares {
        class server.model.squares.SpawnPoint {
            - weaponToDropIndex : int
            - weaponToGrabIndex : int
            - weapons : WeaponCard[]
            - weaponsDeck : Deck<WeaponCard>
            + SpawnPoint()
            + SpawnPoint()
            + collect()
            + convertToDTO()
            + getWeaponToDropIndex()
            + getWeapons()
            + init()
            + isEmpty()
            + isSpawnPoint()
            + itemToString()
            + refill()
            + resetWeaponIndexes()
            + setWeaponToDropIndex()
            + setWeaponToGrabIndex()
            + weaponAtIndex()
            - convertWeaponsDTO()
        }
      }
    }
  }
  

  namespace server {
    namespace model {
      namespace squares {
        abstract class server.model.squares.Square {
            ~ isSpawnPoint : boolean
            - col : int
            - marked : boolean
            - pcs : HashSet<Pc>
            - row : int
            - targetable : boolean
            - visibles : HashSet<Square>
            + Square()
            + Square()
            + addModelEventHandler()
            + addPc()
            + addVisible()
            + allSquares()
            + allSquaresOnDirection()
            + atDistance()
            {abstract} + collect()
            {abstract} + convertToDTO()
            + description()
            + getCol()
            + getColour()
            + getPcs()
            + getRow()
            + getVisibles()
            {abstract} + init()
            {abstract} + isEmpty()
            + isMarked()
            {abstract} + isSpawnPoint()
            + isTargetable()
            {abstract} + itemToString()
            + onDirection()
            {abstract} + refill()
            + removePc()
            + resetWeaponIndexes()
            + setMarked()
            + setTargetable()
            + setWeaponToDropIndex()
            + setWeaponToGrabIndex()
            + toString()
        }
      }
    }
  }
  

  server.model.squares.AmmoSquare -up-|> server.model.squares.Square
  server.model.squares.AmmoSquare o-- server.model.AmmoTile : ammoTile
  server.model.squares.SpawnPoint -up-|> server.model.squares.Square
  server.model.squares.Square o-- server.model.ModelEventHandler : events
  server.model.squares.Square o-- common.enums.SquareColourEnum : colour


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
