@startuml

title __PC_BOARD's Class Diagram__\n

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni {
                  - azioniImages : ImageView
                  - mainPane : StackPane
                  + changed()
                  + setColor()
                  + setPlayer()
                  ~ widthProperty()
                  - collectButton()
                  - moveButton()
                  - shootButton()
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard {
                  - HEIGHT : DoubleProperty
                  - immagine : ImageView
                  - mainPane : VBox
                  - powerups : HBox
                  - weapons : HBox
                  + heightProperty()
                  + initialize()
                  + onChanged()
                  + setColor()
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard {
                  {static} + HEIGHT : Double
                  + frenzyListener : ChangeListener<KillShotTrackDTO>
                  {static} ~ DIRECTORY : String
                  {static} ~ FRENZY_SUBDIR : String
                  ~ translating : HBox
                  - immagine : ImageView
                  - mainPane : HBox
                  - translate : TranslateTransition
                  + changed()
                  + initialize()
                  + onChanged()
                  + setPcColour()
                  + setPlayer()
                  - appear()
                  - disappear()
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.Vita {
                  - background : ImageView
                  - danni : TilePane
                  - mainPane : StackPane
                  - marchi : GridPane
                  - morti : TilePane
                  + changed()
                  + fitHeightProperty()
                  + initialize()
                  + onChanged()
                  + setColor()
                  + widthProperty()
                  - test()
                  - updateDamageTrack()
                  - updateKills()
                  - updateMarks()
              }
            }
          }
        }
      }
    }
  }
  

  client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni o-- common.enums.PcColourEnum : color
  client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard o-- client.gui.view.javafx_controllers.in_game.components.Ammo : ammosController
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard o-- common.enums.PcColourEnum : settedColor
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard o-- client.gui.view.javafx_controllers.in_game.components.pc_board.Vita : vitaController
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard o-- client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni : azioniController
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard o-- common.enums.PcColourEnum : settedColour
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard o-- client.gui.view.javafx_controllers.in_game.components.pc_board.Vita : vitaController
  client.gui.view.javafx_controllers.in_game.components.pc_board.Vita .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.Vita .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.Vita o-- common.enums.PcColourEnum : settedColor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
