@startuml

title __JAVAFX_CONTROLLERS's Class Diagram__\n

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        abstract class client.gui.view.javafx_controllers.AbstractJavaFxController {
            # hostServices : HostServices
            {abstract} + ack()
            {abstract} + acquireConnection()
            {abstract} + acquireConnectionMethod()
            {abstract} + acquireToken()
            {abstract} + acquireUsername()
            {abstract} + authMethod()
            {abstract} + chatMessage()
            + error()
            {abstract} + notifyEvent()
            {abstract} + onGameBoardUpdate()
            {abstract} + onKillShotTrackUpdate()
            {abstract} + onPcBoardUpdate()
            {abstract} + onPcUpdate()
            {abstract} + onSquareUpdate()
            {abstract} + request()
            {abstract} + resumeGame()
            + setHostServices()
            + setPlayer()
            + setTopView()
            # AbstractJavaFxController()
        }
      }
    }
  }
  

  client.gui.view.javafx_controllers.AbstractJavaFxController .up.|> common.events.ModelEventListener
  client.gui.view.javafx_controllers.AbstractJavaFxController .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.AbstractJavaFxController o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.AbstractJavaFxController o-- client.gui.view.GuiView : topView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
