@startuml

title __GUI's Class Diagram__\n

  namespace client.gui {
    class client.gui.ImageCache {
    }
  }
  

  namespace client.gui {
    class client.gui.LaunchGui {
    }
  }
  

  namespace client.gui {
    namespace controller {
      class client.gui.controller.GuiController {
      }
    }
  }
  

  namespace client.gui {
    namespace controller {
      class client.gui.controller.GuiExceptionHandler {
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      class client.gui.view.GuiView {
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        abstract class client.gui.view.javafx_controllers.AbstractJavaFxController {
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace authentication {
          class client.gui.view.javafx_controllers.authentication.UserAuthController {
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace game_setup {
          class client.gui.view.javafx_controllers.game_setup.SetupController {
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          class client.gui.view.javafx_controllers.in_game.InGameController {
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            class client.gui.view.javafx_controllers.in_game.components.Ammo {
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            class client.gui.view.javafx_controllers.in_game.components.Chat {
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            class client.gui.view.javafx_controllers.in_game.components.Map {
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            class client.gui.view.javafx_controllers.in_game.components.Top {
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace card_spaces {
              class client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder {
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace card_spaces {
              namespace player_hands {
                abstract class client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.CardHand {
                }
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace card_spaces {
              namespace player_hands {
                class client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.PowerUpHand {
                }
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace card_spaces {
              namespace player_hands {
                class client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.WeaponHand {
                }
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni {
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard {
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard {
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace pc_board {
              class client.gui.view.javafx_controllers.in_game.components.pc_board.Vita {
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace weapons {
              class client.gui.view.javafx_controllers.in_game.components.weapons.GeneralWeapon {
              }
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace dialogs {
            class client.gui.view.javafx_controllers.in_game.dialogs.SettingsMenu {
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace dialogs {
            class client.gui.view.javafx_controllers.in_game.dialogs.TagbackRequest {
            }
          }
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace view_states {
        class client.gui.view.view_states.InGameState {
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace view_states {
        class client.gui.view.view_states.SetupState {
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace view_states {
        class client.gui.view.view_states.UserAuthState {
        }
      }
    }
  }
  

  namespace client.gui {
    namespace view {
      namespace view_states {
        abstract class client.gui.view.view_states.ViewState {
        }
      }
    }
  }
  

  client.gui.controller.GuiController -up-|> javafx.application.Application
  client.gui.controller.GuiController o-- common.remote_interfaces.RemotePlayer : player
  client.gui.controller.GuiController o-- client.gui.view.GuiView : view
  client.gui.controller.GuiController o-- common.remote_interfaces.RemoteLoginController : loginController
  client.gui.controller.GuiExceptionHandler .up.|> java.lang.Thread.UncaughtExceptionHandler
  client.gui.controller.GuiExceptionHandler o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.GuiView .up.|> common.events.ModelEventListener
  client.gui.view.GuiView -up-|> client.view.AbstractView
  client.gui.view.GuiView o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.GuiView o-- client.gui.view.view_states.ViewState : currentGui
  client.gui.view.javafx_controllers.AbstractJavaFxController .up.|> common.events.ModelEventListener
  client.gui.view.javafx_controllers.AbstractJavaFxController .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.AbstractJavaFxController o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.AbstractJavaFxController o-- client.gui.view.GuiView : topView
  client.gui.view.javafx_controllers.authentication.UserAuthController -up-|> client.gui.view.javafx_controllers.AbstractJavaFxController
  client.gui.view.javafx_controllers.game_setup.SetupController -up-|> client.gui.view.javafx_controllers.AbstractJavaFxController
  client.gui.view.javafx_controllers.game_setup.SetupController o-- client.gui.view.javafx_controllers.in_game.components.Chat : chatController
  client.gui.view.javafx_controllers.in_game.InGameController -up-|> client.gui.view.javafx_controllers.AbstractJavaFxController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder : cardHolderLeftController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder : cardHolderRightController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.Chat : chatController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.Map : mapController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard : pcBoardController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.PowerUpHand : powerUpHandController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.Top : topController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.WeaponHand : weaponHandController
  client.gui.view.javafx_controllers.in_game.components.Ammo .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.Ammo .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.Ammo o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.Ammo o-- common.enums.PcColourEnum : settedColor
  client.gui.view.javafx_controllers.in_game.components.Chat o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.Map o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.Top .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.Top o-- client.gui.view.javafx_controllers.in_game.components.Ammo : ammoController
  client.gui.view.javafx_controllers.in_game.components.Top o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder : cardHolderController
  client.gui.view.javafx_controllers.in_game.components.Top o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.Top o-- common.enums.PcColourEnum : settedColour
  client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder o-- common.enums.SquareColourEnum : squareColor
  client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.CardHand o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.CardHand o-- common.enums.PcColourEnum : playerColor
  client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.PowerUpHand -up-|> client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.CardHand
  client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.WeaponHand -up-|> client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.CardHand
  client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni o-- common.enums.PcColourEnum : color
  client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard o-- client.gui.view.javafx_controllers.in_game.components.Ammo : ammosController
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard o-- common.enums.PcColourEnum : settedColor
  client.gui.view.javafx_controllers.in_game.components.pc_board.OpponentBoard o-- client.gui.view.javafx_controllers.in_game.components.pc_board.Vita : vitaController
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard o-- client.gui.view.javafx_controllers.in_game.components.pc_board.Azioni : azioniController
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard o-- common.enums.PcColourEnum : settedColour
  client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard o-- client.gui.view.javafx_controllers.in_game.components.pc_board.Vita : vitaController
  client.gui.view.javafx_controllers.in_game.components.pc_board.Vita .up.|> javafx.beans.value.ChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.Vita .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.pc_board.Vita o-- common.enums.PcColourEnum : settedColor
  client.gui.view.javafx_controllers.in_game.components.weapons.GeneralWeapon o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.dialogs.SettingsMenu o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.view_states.InGameState -up-|> client.gui.view.view_states.ViewState
  client.gui.view.view_states.SetupState -up-|> client.gui.view.view_states.ViewState
  client.gui.view.view_states.UserAuthState -up-|> client.gui.view.view_states.ViewState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
