@startuml

title __DESERIALIZERS's Class Diagram__\n

  namespace server {
    namespace model {
      namespace deserializers {
        class server.model.deserializers.ActionDeserializer {
            + deserialize()
        }
      }
    }
  }
  

  namespace server {
    namespace model {
      namespace deserializers {
        class server.model.deserializers.AmmoDeckDeserializer {
            + deserialize()
        }
      }
    }
  }
  

  namespace server {
    namespace model {
      namespace deserializers {
        class server.model.deserializers.PowerUpsDeckDeserializer {
            + deserialize()
        }
      }
    }
  }
  

  namespace server {
    namespace model {
      namespace deserializers {
        class server.model.deserializers.SquareDeserializer {
            + deserialize()
        }
      }
    }
  }
  

  namespace server {
    namespace model {
      namespace deserializers {
        class server.model.deserializers.WeaponsDeckDeserializer {
            + deserialize()
        }
      }
    }
  }
  

  server.model.deserializers.ActionDeserializer .up.|> com.google.gson.JsonDeserializer
  server.model.deserializers.AmmoDeckDeserializer .up.|> com.google.gson.JsonDeserializer
  server.model.deserializers.PowerUpsDeckDeserializer .up.|> com.google.gson.JsonDeserializer
  server.model.deserializers.SquareDeserializer .up.|> com.google.gson.JsonDeserializer
  server.model.deserializers.WeaponsDeckDeserializer .up.|> com.google.gson.JsonDeserializer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
