@startuml

title __GAME_SETUP's Class Diagram__\n

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace game_setup {
          class client.gui.view.javafx_controllers.game_setup.SetupController {
              {static} - LENGHT : int
              - circles : Circle[]
              - firstPlayer : boolean
              - mainPane : GridPane
              - maps : TilePane
              - pcViews : EnumMap<PcColourEnum, ImageView>
              - pcs : HBox
              {static} - selectableEffect : Effect
              - selectedSkulls : int
              - skullPanes : StackPane[]
              - skullTrack : HBox
              + SetupController()
              + ack()
              + acquireConnection()
              + acquireConnectionMethod()
              + acquireToken()
              + acquireUsername()
              + authMethod()
              + changed()
              + chatMessage()
              + initialize()
              + notifyEvent()
              + onGameBoardUpdate()
              + onKillShotTrackUpdate()
              + onPcBoardUpdate()
              + onPcUpdate()
              + onSquareUpdate()
              + request()
              + resumeGame()
              + setPlayer()
              + winners()
              - chooseMap()
              - choosePcColor()
              - chooseSkulls()
              - setEnabled()
              - setMapSelectable()
              - setPcSelectable()
              - setPcSelected()
              - setSkullsSelectable()
              - showCirclesBeforeIndex()
          }
        }
      }
    }
  }
  

  client.gui.view.javafx_controllers.game_setup.SetupController -up-|> client.gui.view.javafx_controllers.AbstractJavaFxController
  client.gui.view.javafx_controllers.game_setup.SetupController o-- client.gui.view.javafx_controllers.in_game.components.Chat : chatController


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
