@startuml

title __IN_GAME's Class Diagram__\n

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          class client.gui.view.javafx_controllers.in_game.InGameController {
              + bottom : HBox
              {static} + selectedObjectEffect : Effect
              - killShotTrack : GridPane
              - killShotTrackData : ObjectProperty<KillShotTrackDTO>
              - mainPane : BorderPane
              - pcs : ObservableMap<PcColourEnum, PcDTO>
              - squares : ObservableMap<SquareDTO, SquareDTO>
              - underMapButtons : HBox
              + InGameController()
              + ack()
              + acquireConnection()
              + acquireConnectionMethod()
              + acquireToken()
              + acquireUsername()
              + authMethod()
              + changed()
              + chatMessage()
              + initialize()
              + notifyEvent()
              + onGameBoardUpdate()
              + onKillShotTrackUpdate()
              + onPcBoardUpdate()
              + onPcUpdate()
              + onSquareUpdate()
              + request()
              + resumeGame()
              + setHostServices()
              + setPlayer()
              + winners()
              - applyClicked()
              - deselectAll()
              - passClicked()
              - reloadClicked()
              - skipClicked()
              - spacerFactory()
              - undoClicked()
          }
        }
      }
    }
  }
  

  client.gui.view.javafx_controllers.in_game.InGameController -up-|> client.gui.view.javafx_controllers.AbstractJavaFxController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder : cardHolderLeftController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder : cardHolderRightController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.Chat : chatController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.Map : mapController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.pc_board.PcBoard : pcBoardController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.PowerUpHand : powerUpHandController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.Top : topController
  client.gui.view.javafx_controllers.in_game.InGameController o-- client.gui.view.javafx_controllers.in_game.components.card_spaces.player_hands.WeaponHand : weaponHandController


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
