@startuml

title __CARD_SPACES's Class Diagram__\n

  namespace client.gui {
    namespace view {
      namespace javafx_controllers {
        namespace in_game {
          namespace components {
            namespace card_spaces {
              class client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder {
                  + mainPane : AnchorPane
                  ~ CARD_TRANSLATION : Double
                  - background : ImageView
                  - cards : ImageView[]
                  - cornerProperty : ObjectProperty<CardinalDirectionEnum>
                  - rotations : RotateTransition[]
                  - showing : ParallelTransition[]
                  - weaponBox : FlowPane
                  + deselectAll()
                  + initialize()
                  + onChanged()
                  + setCards()
                  + setColor()
                  + setCorner()
                  + setPlayer()
                  - appear()
                  - chooseWeaponOnSpawnPoint()
                  - disappear()
              }
            }
          }
        }
      }
    }
  }
  

  client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder .up.|> javafx.collections.MapChangeListener
  client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder o-- common.remote_interfaces.RemotePlayer : player
  client.gui.view.javafx_controllers.in_game.components.card_spaces.CardHolder o-- common.enums.SquareColourEnum : squareColor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
