@startuml

title __PC_BOARD_EVENTS's Class Diagram__\n

  namespace common {
    namespace events {
      namespace pc_board_events {
        class common.events.pc_board_events.AmmoChangedEvent {
            - ammoDifference : short[]
            - eventID : int
            - isEarned : boolean
            - powerUpsDiscarded : List<String>
            + AmmoChangedEvent()
            + censor()
            + toString()
            - AmmoChangedEvent()
            - ammoDifferenceToString()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace pc_board_events {
        class common.events.pc_board_events.DamageMarksTakenEvent {
            - damage : short
            - eventID : int
            - marks : short
            - shooter : String
            + DamageMarksTakenEvent()
            + censor()
            + toString()
            - DamageMarksTakenEvent()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace pc_board_events {
        class common.events.pc_board_events.DeathEvent {
            - eventID : int
            + DeathEvent()
            + censor()
            + toString()
            - DeathEvent()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace pc_board_events {
        class common.events.pc_board_events.NumberOfDeathIncreasedEvent {
            - eventID : int
            + NumberOfDeathIncreasedEvent()
            + censor()
            + toString()
            - NumberOfDeathIncreasedEvent()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace pc_board_events {
        abstract class common.events.pc_board_events.PcBoardEvent {
            ~ censored : boolean
            {abstract} + censor()
            + getDTO()
            ~ PcBoardEvent()
            ~ PcBoardEvent()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace pc_board_events {
        class common.events.pc_board_events.PointsIncreasedEvents {
            - earnedPoints : int
            - eventID : int
            + PointsIncreasedEvents()
            + censor()
            + toString()
            - PointsIncreasedEvents()
        }
      }
    }
  }
  

  common.events.pc_board_events.AmmoChangedEvent -up-|> common.events.pc_board_events.PcBoardEvent
  common.events.pc_board_events.DamageMarksTakenEvent -up-|> common.events.pc_board_events.PcBoardEvent
  common.events.pc_board_events.DeathEvent -up-|> common.events.pc_board_events.PcBoardEvent
  common.events.pc_board_events.NumberOfDeathIncreasedEvent -up-|> common.events.pc_board_events.PcBoardEvent
  common.events.pc_board_events.PcBoardEvent .up.|> common.events.ModelEvent
  common.events.pc_board_events.PcBoardEvent o-- common.dto_model.PcBoardDTO : pcBoard
  common.events.pc_board_events.PointsIncreasedEvents -up-|> common.events.pc_board_events.PcBoardEvent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
