@startuml

title __COMMON's Class Diagram__\n

  namespace common {
    abstract class common.AbstractSocketProxy {
        # in : BufferedReader
        # out : PrintWriter
        # socket : Socket
        + AbstractSocketProxy()
    }
  }
  

  namespace common {
    class common.Constants {
        {static} + ACTIONS_PER_FRENZY_TURN_AFTER_FIRST_PLAYER : int
        {static} + ACTIONS_PER_TURN : int
        {static} + ADRENALINE_UP : int
        {static} + AMMO_CHANGED : int
        {static} + AMMO_COLOURS_NUMBER : int
        {static} + CARDS_ON_SPAWN_POINT : int
        {static} + COLLECT_EVENT : int
        {static} + DAMAGE_MARKS_TAKEN : int
        {static} + DEATH : int
        {static} + FAIL : String
        {static} + FINAL_FRENZY : int
        {static} + FINAL_FRENZY_PC_VALUES : int[]
        {static} + FIRST_MAP : int
        {static} + GAME_BOARD_SET : int
        {static} + ITEM_COLLECTED : int
        {static} + KILL_SHOT_TRACK_SET : int
        {static} + LAST_MAP : int
        {static} + LIFE_POINTS : int
        {static} + MAX_AMMO_PER_COLOUR : int
        {static} + MAX_KILL_SHOT_TRACK_SIZE : int
        {static} + MAX_NUMBER_OF_MARKS_PER_COLOUR : int
        {static} + MAX_POWER_UPS_IN_HAND : int
        {static} + MAX_WEAPONS_IN_HAND : int
        {static} + MIN_KILL_SHOT_TRACK_SIZE : int
        {static} + MOVEMENT : int
        {static} + NUMBER_OF_DEATH_INCREASED : int
        {static} + PC_COLOUR_CHOSEN : int
        {static} + PC_VALUES : int[]
        {static} + PLAYER_JOINED : int
        {static} + POINTS_INCREASED : int
        {static} + POWER_UP_DISCARDED : int
        {static} + POWER_UP_DROWN : int
        {static} + REGEX : String
        {static} + SPAWN : int
        {static} + SQUARE_REFILLED : int
        {static} + SUCCESS : String
        {static} + TARGETABLE_SET : int
        {static} + WRONG_TIME : String
        ~ Constants()
    }
  }
  

  namespace common {
    class common.ModelEventDeserializer {
        + deserialize()
    }
  }
  

  namespace common {
    abstract class common.PropertyLoader {
        # properties : Properties
        {static} - FILENAME : String
        {static} - sharedProps : String[]
        + getHostAddress()
        + getRequestTimer()
        + getRmiPort()
        + getSocketPort()
        # PropertyLoader()
    }
  }
  

  common.ModelEventDeserializer .up.|> com.google.gson.JsonDeserializer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
