@startuml

title __ENUMS's Class Diagram__\n

  namespace common {
    namespace enums {
      enum AmmoEnum {
        BLUE
        RED
        YELLOW
        tabs
      }
    }
  }
  

  namespace common {
    namespace enums {
      enum CardinalDirectionEnum {
        EAST
        NORTH
        SOUTH
        WEST
        abbreviation
      }
    }
  }
  

  namespace common {
    namespace enums {
      enum ConnectionMethodEnum {
        QUIT
        RMI
        SOCKET
        command
      }
    }
  }
  

  namespace common {
    namespace enums {
      enum ControllerMethodsEnum {
        CHOOSE_AMMO
        CHOOSE_ASYNCHRONOUS_EFFECT_ORDER
        CHOOSE_DIRECTION
        CHOOSE_MAP
        CHOOSE_NUMBER_OF_SKULLS
        CHOOSE_PC_COLOUR
        CHOOSE_POWER_UP
        CHOOSE_SQUARE
        CHOOSE_TARGET
        CHOOSE_UPGRADE
        CHOOSE_WEAPON_OF_MINE
        CHOOSE_WEAPON_ON_SPAWN_POINT
        GRAB_STUFF
        HELP
        JOIN_LOBBY
        LOG_IN
        OK
        PASS
        QUIT
        RELOAD
        RESPONSE
        RUN_AROUND
        SEND_MESSAGE
        SHOOT_PEOPLE
        SHOW_COMMENT
        SIGN_UP
        SKIP
        SWITCH_FIRE_MODE
        UNDO
        USE_POWER_UP
        command
        description
      }
    }
  }
  

  namespace common {
    namespace enums {
      enum PcColourEnum {
        BLUE
        GREEN
        GREY
        PURPLE
        YELLOW
        description
        name
        tabs
      }
    }
  }
  

  namespace common {
    namespace enums {
      enum SquareColourEnum {
        BLUE
        GREEN
        RED
        VIOLET
        WHITE
        YELLOW
      }
    }
  }
  

  namespace common {
    namespace enums {
      enum ViewMethodsEnum {
        ACK
        CHAT_MESSAGE
        CLOSE
        ERROR
        NOTIFY_EVENT
        ON_GAME_BOARD_UPDATE
        ON_KILL_SHOT_TRACK_UPDATE
        ON_PC_BOARD_UPDATE
        ON_PC_UPDATE
        ON_SQUARE_UPDATE
        REQUEST
        RESUME_GAME
        WINNERS
      }
    }
  }
  

  common.enums.PcColourEnum .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
