@startuml

title __SQUARE_EVENTS's Class Diagram__\n

  namespace common {
    namespace events {
      namespace square_events {
        class common.events.square_events.ItemCollectedEvent {
            - eventID : int
            - item : String
            + ItemCollectedEvent()
            + censor()
            + toString()
            - ItemCollectedEvent()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace square_events {
        abstract class common.events.square_events.SquareEvent {
            ~ isPrivate : boolean
            {abstract} + censor()
            + getDTO()
            + getPublisherColour()
            ~ SquareEvent()
            ~ SquareEvent()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace square_events {
        class common.events.square_events.SquareRefilledEvent {
            - eventID : int
            - isSpawnPoint : boolean
            + SquareRefilledEvent()
            + censor()
            + toString()
            - SquareRefilledEvent()
        }
      }
    }
  }
  

  namespace common {
    namespace events {
      namespace square_events {
        class common.events.square_events.TargetableSetEvent {
            - eventID : int
            + TargetableSetEvent()
            + censor()
            + toString()
            - TargetableSetEvent()
        }
      }
    }
  }
  

  common.events.square_events.ItemCollectedEvent -up-|> common.events.square_events.SquareEvent
  common.events.square_events.ItemCollectedEvent o-- common.enums.PcColourEnum : pcColour
  common.events.square_events.SquareEvent .up.|> common.events.ModelEvent
  common.events.square_events.SquareEvent o-- common.dto_model.SquareDTO : square
  common.events.square_events.SquareRefilledEvent -up-|> common.events.square_events.SquareEvent
  common.events.square_events.TargetableSetEvent -up-|> common.events.square_events.SquareEvent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
